name: Update marketplace
on:
  push:
    branches: "main"
    paths:
      - action.yml
      - .github/workflows/update-marketplace.yml
jobs:
  update-marketplace:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git tag marketplace --force
      - run: git push origin marketplace --force
