name: Test action
on:
  issues:
    types: labeled
jobs:
  test-action:
    if: github.event.label.name == 'lorem ipsum'
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - run: gh issue comment "$NUMBER" --repo "$REPO" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
          BODY: >
            Lorem ipsum is placeholder text commonly used in the graphic, print,
            and publishing industries for previewing layouts and visual mockups.
      - run: gh issue close "$NUMBER" --repo "$REPO"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
